package proyectoalgoritmosordenamiento;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 @author Jason
 */
public class PantallaPrincipal extends javax.swing.JFrame
{
    DefaultTableModel modelo;
    TableRowSorter sort;
        
    Tenista tenista = new Tenista();
    
    Tenista[] listaTenista = new Tenista[15];
    int contadorTenista = 0; //Lleva el recuento de tenistas.
    
    Tenista[] listaTenistaAux = new Tenista[15];
    int contadorTenistaAux = 0;
    
    String[] listaPuntajes = new String[15];
    
    
    /**
     Creates new form PantallaPrincipal
     */
    public PantallaPrincipal()
    {
        initComponents();
        
        //cambia el icono del formulario principal.
        setIconImage(new ImageIcon(getClass().getResource("/resources/tennis.png")).getImage());
        
        //Dibuja la tabla.
        modelo = new DefaultTableModel();
        modelo.addColumn("Tenista");
        modelo.addColumn("País");
        modelo.addColumn("Edad");
        modelo.addColumn("Puntaje");
        this.tblTenistas.setModel(modelo);
        
        sort = new TableRowSorter(tblTenistas.getModel());
        tblTenistas.setRowSorter(sort);
        
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbMetodosOrdenamiento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtPuntaje = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTenistas = new javax.swing.JTable();
        rdbPuntajeDesendente = new javax.swing.JRadioButton();
        rdbEdadAsendente = new javax.swing.JRadioButton();
        rdbAlfafetico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tenistas");
        setBackground(java.awt.SystemColor.activeCaption);

        btnSalir.setBackground(java.awt.SystemColor.inactiveCaption);
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSalir.setForeground(java.awt.SystemColor.controlDkShadow);
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel1.setText("Método de ordenamiento:");

        btnActualizar.setBackground(java.awt.SystemColor.inactiveCaption);
        btnActualizar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnActualizar.setForeground(java.awt.SystemColor.controlDkShadow);
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setFocusPainted(false);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnActualizarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");

        cmbMetodosOrdenamiento.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbMetodosOrdenamiento.setForeground(java.awt.SystemColor.controlDkShadow);
        cmbMetodosOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Insercción", "Burbuja" }));
        cmbMetodosOrdenamiento.setBorder(null);
        cmbMetodosOrdenamiento.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel3.setText("Nombre completo:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel4.setText("País:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel6.setText("Puntaje:");

        txtNombreCompleto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNombreCompleto.setForeground(java.awt.SystemColor.controlDkShadow);
        txtNombreCompleto.setBorder(null);

        txtPais.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPais.setForeground(java.awt.SystemColor.controlDkShadow);
        txtPais.setBorder(null);

        txtEdad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEdad.setForeground(java.awt.SystemColor.controlDkShadow);
        txtEdad.setBorder(null);

        txtPuntaje.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPuntaje.setForeground(java.awt.SystemColor.controlDkShadow);
        txtPuntaje.setBorder(null);

        btnAgregar.setBackground(java.awt.SystemColor.inactiveCaption);
        btnAgregar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAgregar.setForeground(java.awt.SystemColor.controlDkShadow);
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setFocusPainted(false);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseClicked(evt);
            }
        });

        tblTenistas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblTenistas.setForeground(java.awt.SystemColor.controlDkShadow);
        tblTenistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null}
            },
            new String []
            {
                "Nombre completo", "País", "Edad", "Puntaje"
            }
        ));
        tblTenistas.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblTenistas);

        rdbPuntajeDesendente.setSelected(true);
        rdbPuntajeDesendente.setText("Puntaje Desc");
        rdbPuntajeDesendente.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                rdbPuntajeDesendenteStateChanged(evt);
            }
        });

        rdbEdadAsendente.setText("Edad Asen");
        rdbEdadAsendente.setEnabled(false);
        rdbEdadAsendente.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                rdbEdadAsendenteStateChanged(evt);
            }
        });

        rdbAlfafetico.setText("Alfabetico");
        rdbAlfafetico.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMetodosOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbPuntajeDesendente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbEdadAsendente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbAlfafetico, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMetodosOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbPuntajeDesendente)
                    .addComponent(rdbEdadAsendente)
                    .addComponent(rdbAlfafetico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseClicked
    {//GEN-HEADEREND:event_btnAgregarMouseClicked
        try
        {
            if((txtNombreCompleto.getText().isEmpty() != true) && (txtPais.getText().isEmpty() != true) &&
                (txtEdad.getText().isEmpty() != true) && (txtPuntaje.getText().isEmpty() != true))
        {
            AgragarDatosTabla();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Hay espacios sin llenar", "Error", JOptionPane.WARNING_MESSAGE);
        }
        }
        catch(Exception err)
        {
            JOptionPane.showMessageDialog(null, err, "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnActualizarMouseClicked
    {//GEN-HEADEREND:event_btnActualizarMouseClicked
        
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void rdbPuntajeDesendenteStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_rdbPuntajeDesendenteStateChanged
    {//GEN-HEADEREND:event_rdbPuntajeDesendenteStateChanged
        if(rdbPuntajeDesendente.isSelected() == true)
        {
            rdbEdadAsendente.setEnabled(false);
            rdbAlfafetico.setEnabled(false);
        }else
        {
            rdbEdadAsendente.setEnabled(true);
            rdbAlfafetico.setEnabled(true);
        }   
    }//GEN-LAST:event_rdbPuntajeDesendenteStateChanged

    private void rdbEdadAsendenteStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_rdbEdadAsendenteStateChanged
    {//GEN-HEADEREND:event_rdbEdadAsendenteStateChanged
        if(rdbEdadAsendente.isSelected() == true)
        {
            rdbPuntajeDesendente.setEnabled(false);
            rdbAlfafetico.setEnabled(false);
        }else
        {
            rdbPuntajeDesendente.setEnabled(true);
            rdbAlfafetico.setEnabled(true);
        } 
    }//GEN-LAST:event_rdbEdadAsendenteStateChanged
    
    public Tenista obtenerDatos()
    {
        Tenista nuevoTenista = new Tenista();
        
        try
        {
            nuevoTenista.setNombre(txtNombreCompleto.getText().trim());
            nuevoTenista.setPais(txtPais.getText().trim());
            nuevoTenista.setEdad(Integer.parseInt(txtEdad.getText()));
            nuevoTenista.setPuntaje(Integer.parseInt(txtPuntaje.getText().trim()));
            
        }catch(Exception err)
        {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error." + err,"Error",JOptionPane.ERROR_MESSAGE);
        }
        return nuevoTenista;
    }
    
    public void AgragarDatosTabla()
    {
        listaTenista[contadorTenista] = obtenerDatos();
        
        String[] filas = new String[4];
        
        if(contadorTenista != 14) //Evalua el número de tenistas que se pueden agregar
        {
            filas[0] = listaTenista[contadorTenista].getNombre();
            filas[1] = listaTenista[contadorTenista].getPais();
            filas[2] = String.valueOf(listaTenista[contadorTenista].getEdad());
            filas[3] = String.valueOf(listaTenista[contadorTenista].getPuntaje());
            modelo.addRow(filas);
            
            contadorTenista++;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Se ha llegado al maximo número de tenistas.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void MetodoBurbuja(int[] lista)
    {
        for (int j = 0; j < 14; j++)
        {
            for(int i = 0; i < (14 - 1); i++) 
            {
                if (lista[i] > lista [i + 1])
                {
                    int aux;
                    aux = lista[i];
                    lista[i] = lista[i + 1];
                    lista[i + 1] = aux;
                }
            }
        }
    }
    
    public void MetodoInsercion(int[] lista)
    {
        int i;
        int clave;
        int j;                

        for (i = 1; i < 14; i++)
        {	   
            clave = lista[i];
            j = i - 1;
            while (j >= 0 && lista[i] > clave)
            {
                    lista[j + 1] = lista[j];
                    j = j - 1;
            }
            lista[j + 1] = clave;
        }
    }
    
    /**
     @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbMetodosOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbAlfafetico;
    private javax.swing.JRadioButton rdbEdadAsendente;
    private javax.swing.JRadioButton rdbPuntajeDesendente;
    private javax.swing.JTable tblTenistas;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPuntaje;
    // End of variables declaration//GEN-END:variables
}
